### ISSUE TITLE
Instant heal on bed.

### ISSUE THREAD

**Issue by pirone2** [baileyholl/Event-Tweaks#1]
If the "heal on sleep" event is active, you get healed the instant you lie on the bed, instead of when you end your sleep, allowing you to cancel the sleep animation and get the benefits for sleeping without ending the night. This means that as long as it's nighttime and there's no monsters nearby you have infinite instant heals. This is specially broken with mods that add sleeping bags or let you sleep during daytime.

**Comment by baileyholl** [comment]
uhhhh whoops. Thanks for that!

**Comment by baileyholl** [comment]
Fixed, new version uploaded.
